//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhajeNasirAccountingSystemWindowsFormClient.ChequeService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cheque", Namespace="http://schemas.datacontract.org/2004/07/KhajeNasirAccountingSystemWcfServiceAppli" +
        "cation")]
    [System.SerializableAttribute()]
    public partial class Cheque : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdminNationalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ConsecutiveNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime IssuanceDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KhajeNasirAccountingSystemWindowsFormClient.ChequeService.People PeopleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdminNationalCode {
            get {
                return this.AdminNationalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AdminNationalCodeField, value) != true)) {
                    this.AdminNationalCodeField = value;
                    this.RaisePropertyChanged("AdminNationalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ConsecutiveNumber {
            get {
                return this.ConsecutiveNumberField;
            }
            set {
                if ((this.ConsecutiveNumberField.Equals(value) != true)) {
                    this.ConsecutiveNumberField = value;
                    this.RaisePropertyChanged("ConsecutiveNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime IssuanceDateTime {
            get {
                return this.IssuanceDateTimeField;
            }
            set {
                if ((this.IssuanceDateTimeField.Equals(value) != true)) {
                    this.IssuanceDateTimeField = value;
                    this.RaisePropertyChanged("IssuanceDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayTo {
            get {
                return this.PayToField;
            }
            set {
                if ((object.ReferenceEquals(this.PayToField, value) != true)) {
                    this.PayToField = value;
                    this.RaisePropertyChanged("PayTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KhajeNasirAccountingSystemWindowsFormClient.ChequeService.People People {
            get {
                return this.PeopleField;
            }
            set {
                if ((object.ReferenceEquals(this.PeopleField, value) != true)) {
                    this.PeopleField = value;
                    this.RaisePropertyChanged("People");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="People", Namespace="http://schemas.datacontract.org/2004/07/KhajeNasirAccountingSystemWcfServiceAppli" +
        "cation")]
    [System.SerializableAttribute()]
    public partial class People : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BirthCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> BirthDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KhajeNasirAccountingSystemWindowsFormClient.ChequeService.Cheque[] ChequesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ContributionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreateDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KhajeNasirAccountingSystemWindowsFormClient.ChequeService.DepositTransaction[] DepositTransactionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KhajeNasirAccountingSystemWindowsFormClient.ChequeService.DepositTransaction[] DepositTransactions1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FathersNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KhajeNasirAccountingSystemWindowsFormClient.ChequeService.LoanTransaction[] LoanTransactionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KhajeNasirAccountingSystemWindowsFormClient.ChequeService.LoanTransaction[] LoanTransactions1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NationalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BirthCity {
            get {
                return this.BirthCityField;
            }
            set {
                if ((object.ReferenceEquals(this.BirthCityField, value) != true)) {
                    this.BirthCityField = value;
                    this.RaisePropertyChanged("BirthCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BirthDate {
            get {
                return this.BirthDateField;
            }
            set {
                if ((this.BirthDateField.Equals(value) != true)) {
                    this.BirthDateField = value;
                    this.RaisePropertyChanged("BirthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KhajeNasirAccountingSystemWindowsFormClient.ChequeService.Cheque[] Cheques {
            get {
                return this.ChequesField;
            }
            set {
                if ((object.ReferenceEquals(this.ChequesField, value) != true)) {
                    this.ChequesField = value;
                    this.RaisePropertyChanged("Cheques");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Contribution {
            get {
                return this.ContributionField;
            }
            set {
                if ((this.ContributionField.Equals(value) != true)) {
                    this.ContributionField = value;
                    this.RaisePropertyChanged("Contribution");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDateTime {
            get {
                return this.CreateDateTimeField;
            }
            set {
                if ((this.CreateDateTimeField.Equals(value) != true)) {
                    this.CreateDateTimeField = value;
                    this.RaisePropertyChanged("CreateDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KhajeNasirAccountingSystemWindowsFormClient.ChequeService.DepositTransaction[] DepositTransactions {
            get {
                return this.DepositTransactionsField;
            }
            set {
                if ((object.ReferenceEquals(this.DepositTransactionsField, value) != true)) {
                    this.DepositTransactionsField = value;
                    this.RaisePropertyChanged("DepositTransactions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KhajeNasirAccountingSystemWindowsFormClient.ChequeService.DepositTransaction[] DepositTransactions1 {
            get {
                return this.DepositTransactions1Field;
            }
            set {
                if ((object.ReferenceEquals(this.DepositTransactions1Field, value) != true)) {
                    this.DepositTransactions1Field = value;
                    this.RaisePropertyChanged("DepositTransactions1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FathersName {
            get {
                return this.FathersNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FathersNameField, value) != true)) {
                    this.FathersNameField = value;
                    this.RaisePropertyChanged("FathersName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KhajeNasirAccountingSystemWindowsFormClient.ChequeService.LoanTransaction[] LoanTransactions {
            get {
                return this.LoanTransactionsField;
            }
            set {
                if ((object.ReferenceEquals(this.LoanTransactionsField, value) != true)) {
                    this.LoanTransactionsField = value;
                    this.RaisePropertyChanged("LoanTransactions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KhajeNasirAccountingSystemWindowsFormClient.ChequeService.LoanTransaction[] LoanTransactions1 {
            get {
                return this.LoanTransactions1Field;
            }
            set {
                if ((object.ReferenceEquals(this.LoanTransactions1Field, value) != true)) {
                    this.LoanTransactions1Field = value;
                    this.RaisePropertyChanged("LoanTransactions1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile {
            get {
                return this.MobileField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileField, value) != true)) {
                    this.MobileField = value;
                    this.RaisePropertyChanged("Mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NationalCode {
            get {
                return this.NationalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.NationalCodeField, value) != true)) {
                    this.NationalCodeField = value;
                    this.RaisePropertyChanged("NationalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Picture {
            get {
                return this.PictureField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureField, value) != true)) {
                    this.PictureField = value;
                    this.RaisePropertyChanged("Picture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode {
            get {
                return this.PostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalCodeField, value) != true)) {
                    this.PostalCodeField = value;
                    this.RaisePropertyChanged("PostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tel {
            get {
                return this.TelField;
            }
            set {
                if ((object.ReferenceEquals(this.TelField, value) != true)) {
                    this.TelField = value;
                    this.RaisePropertyChanged("Tel");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DepositTransaction", Namespace="http://schemas.datacontract.org/2004/07/KhajeNasirAccountingSystemWcfServiceAppli" +
        "cation")]
    [System.SerializableAttribute()]
    public partial class DepositTransaction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdminNationalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AdminPermissionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankFollowUpCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KhajeNasirAccountingSystemWindowsFormClient.ChequeService.People PeopleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KhajeNasirAccountingSystemWindowsFormClient.ChequeService.People People1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonNationalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessfulField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdminNationalCode {
            get {
                return this.AdminNationalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AdminNationalCodeField, value) != true)) {
                    this.AdminNationalCodeField = value;
                    this.RaisePropertyChanged("AdminNationalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AdminPermission {
            get {
                return this.AdminPermissionField;
            }
            set {
                if ((this.AdminPermissionField.Equals(value) != true)) {
                    this.AdminPermissionField = value;
                    this.RaisePropertyChanged("AdminPermission");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankFollowUpCode {
            get {
                return this.BankFollowUpCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BankFollowUpCodeField, value) != true)) {
                    this.BankFollowUpCodeField = value;
                    this.RaisePropertyChanged("BankFollowUpCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTime {
            get {
                return this.DateTimeField;
            }
            set {
                if ((this.DateTimeField.Equals(value) != true)) {
                    this.DateTimeField = value;
                    this.RaisePropertyChanged("DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KhajeNasirAccountingSystemWindowsFormClient.ChequeService.People People {
            get {
                return this.PeopleField;
            }
            set {
                if ((object.ReferenceEquals(this.PeopleField, value) != true)) {
                    this.PeopleField = value;
                    this.RaisePropertyChanged("People");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KhajeNasirAccountingSystemWindowsFormClient.ChequeService.People People1 {
            get {
                return this.People1Field;
            }
            set {
                if ((object.ReferenceEquals(this.People1Field, value) != true)) {
                    this.People1Field = value;
                    this.RaisePropertyChanged("People1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonNationalCode {
            get {
                return this.PersonNationalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonNationalCodeField, value) != true)) {
                    this.PersonNationalCodeField = value;
                    this.RaisePropertyChanged("PersonNationalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Successful {
            get {
                return this.SuccessfulField;
            }
            set {
                if ((this.SuccessfulField.Equals(value) != true)) {
                    this.SuccessfulField = value;
                    this.RaisePropertyChanged("Successful");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoanTransaction", Namespace="http://schemas.datacontract.org/2004/07/KhajeNasirAccountingSystemWcfServiceAppli" +
        "cation")]
    [System.SerializableAttribute()]
    public partial class LoanTransaction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdminNationalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AdminPermissionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankFollowUpCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> ForContributionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KhajeNasirAccountingSystemWindowsFormClient.ChequeService.Installement[] InstallementsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KhajeNasirAccountingSystemWindowsFormClient.ChequeService.People PeopleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KhajeNasirAccountingSystemWindowsFormClient.ChequeService.People People1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonNationalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessfulField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdminNationalCode {
            get {
                return this.AdminNationalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AdminNationalCodeField, value) != true)) {
                    this.AdminNationalCodeField = value;
                    this.RaisePropertyChanged("AdminNationalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AdminPermission {
            get {
                return this.AdminPermissionField;
            }
            set {
                if ((this.AdminPermissionField.Equals(value) != true)) {
                    this.AdminPermissionField = value;
                    this.RaisePropertyChanged("AdminPermission");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankFollowUpCode {
            get {
                return this.BankFollowUpCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BankFollowUpCodeField, value) != true)) {
                    this.BankFollowUpCodeField = value;
                    this.RaisePropertyChanged("BankFollowUpCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTime {
            get {
                return this.DateTimeField;
            }
            set {
                if ((this.DateTimeField.Equals(value) != true)) {
                    this.DateTimeField = value;
                    this.RaisePropertyChanged("DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> ForContribution {
            get {
                return this.ForContributionField;
            }
            set {
                if ((this.ForContributionField.Equals(value) != true)) {
                    this.ForContributionField = value;
                    this.RaisePropertyChanged("ForContribution");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KhajeNasirAccountingSystemWindowsFormClient.ChequeService.Installement[] Installements {
            get {
                return this.InstallementsField;
            }
            set {
                if ((object.ReferenceEquals(this.InstallementsField, value) != true)) {
                    this.InstallementsField = value;
                    this.RaisePropertyChanged("Installements");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KhajeNasirAccountingSystemWindowsFormClient.ChequeService.People People {
            get {
                return this.PeopleField;
            }
            set {
                if ((object.ReferenceEquals(this.PeopleField, value) != true)) {
                    this.PeopleField = value;
                    this.RaisePropertyChanged("People");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KhajeNasirAccountingSystemWindowsFormClient.ChequeService.People People1 {
            get {
                return this.People1Field;
            }
            set {
                if ((object.ReferenceEquals(this.People1Field, value) != true)) {
                    this.People1Field = value;
                    this.RaisePropertyChanged("People1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonNationalCode {
            get {
                return this.PersonNationalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonNationalCodeField, value) != true)) {
                    this.PersonNationalCodeField = value;
                    this.RaisePropertyChanged("PersonNationalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Successful {
            get {
                return this.SuccessfulField;
            }
            set {
                if ((this.SuccessfulField.Equals(value) != true)) {
                    this.SuccessfulField = value;
                    this.RaisePropertyChanged("Successful");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Installement", Namespace="http://schemas.datacontract.org/2004/07/KhajeNasirAccountingSystemWcfServiceAppli" +
        "cation")]
    [System.SerializableAttribute()]
    public partial class Installement : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPayedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KhajeNasirAccountingSystemWindowsFormClient.ChequeService.LoanTransaction LoanTransactionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid LoanTransactionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> PaymentDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPayed {
            get {
                return this.IsPayedField;
            }
            set {
                if ((this.IsPayedField.Equals(value) != true)) {
                    this.IsPayedField = value;
                    this.RaisePropertyChanged("IsPayed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KhajeNasirAccountingSystemWindowsFormClient.ChequeService.LoanTransaction LoanTransaction {
            get {
                return this.LoanTransactionField;
            }
            set {
                if ((object.ReferenceEquals(this.LoanTransactionField, value) != true)) {
                    this.LoanTransactionField = value;
                    this.RaisePropertyChanged("LoanTransaction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid LoanTransactionId {
            get {
                return this.LoanTransactionIdField;
            }
            set {
                if ((this.LoanTransactionIdField.Equals(value) != true)) {
                    this.LoanTransactionIdField = value;
                    this.RaisePropertyChanged("LoanTransactionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PaymentDate {
            get {
                return this.PaymentDateField;
            }
            set {
                if ((this.PaymentDateField.Equals(value) != true)) {
                    this.PaymentDateField = value;
                    this.RaisePropertyChanged("PaymentDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ChequeService.IChequeService")]
    public interface IChequeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChequeService/GetCheque", ReplyAction="http://tempuri.org/IChequeService/GetChequeResponse")]
        KhajeNasirAccountingSystemWindowsFormClient.ChequeService.Cheque[] GetCheque();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChequeService/GetCheque", ReplyAction="http://tempuri.org/IChequeService/GetChequeResponse")]
        System.Threading.Tasks.Task<KhajeNasirAccountingSystemWindowsFormClient.ChequeService.Cheque[]> GetChequeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChequeService/InsertCheque", ReplyAction="http://tempuri.org/IChequeService/InsertChequeResponse")]
        void InsertCheque(System.Guid Id, decimal Amount, string PayTo, string AdminNationalCode, System.DateTime IssuanceDateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChequeService/InsertCheque", ReplyAction="http://tempuri.org/IChequeService/InsertChequeResponse")]
        System.Threading.Tasks.Task InsertChequeAsync(System.Guid Id, decimal Amount, string PayTo, string AdminNationalCode, System.DateTime IssuanceDateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChequeService/UpdateCheque", ReplyAction="http://tempuri.org/IChequeService/UpdateChequeResponse")]
        void UpdateCheque(System.Guid Id, decimal Amount, string PayTo, string AdminNationalCode, System.DateTime IssuanceDateTime, string Description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChequeService/UpdateCheque", ReplyAction="http://tempuri.org/IChequeService/UpdateChequeResponse")]
        System.Threading.Tasks.Task UpdateChequeAsync(System.Guid Id, decimal Amount, string PayTo, string AdminNationalCode, System.DateTime IssuanceDateTime, string Description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChequeService/DeleteCheque", ReplyAction="http://tempuri.org/IChequeService/DeleteChequeResponse")]
        void DeleteCheque(System.Guid Original_Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChequeService/DeleteCheque", ReplyAction="http://tempuri.org/IChequeService/DeleteChequeResponse")]
        System.Threading.Tasks.Task DeleteChequeAsync(System.Guid Original_Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChequeServiceChannel : KhajeNasirAccountingSystemWindowsFormClient.ChequeService.IChequeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChequeServiceClient : System.ServiceModel.ClientBase<KhajeNasirAccountingSystemWindowsFormClient.ChequeService.IChequeService>, KhajeNasirAccountingSystemWindowsFormClient.ChequeService.IChequeService {
        
        public ChequeServiceClient() {
        }
        
        public ChequeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChequeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChequeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChequeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public KhajeNasirAccountingSystemWindowsFormClient.ChequeService.Cheque[] GetCheque() {
            return base.Channel.GetCheque();
        }
        
        public System.Threading.Tasks.Task<KhajeNasirAccountingSystemWindowsFormClient.ChequeService.Cheque[]> GetChequeAsync() {
            return base.Channel.GetChequeAsync();
        }
        
        public void InsertCheque(System.Guid Id, decimal Amount, string PayTo, string AdminNationalCode, System.DateTime IssuanceDateTime) {
            base.Channel.InsertCheque(Id, Amount, PayTo, AdminNationalCode, IssuanceDateTime);
        }
        
        public System.Threading.Tasks.Task InsertChequeAsync(System.Guid Id, decimal Amount, string PayTo, string AdminNationalCode, System.DateTime IssuanceDateTime) {
            return base.Channel.InsertChequeAsync(Id, Amount, PayTo, AdminNationalCode, IssuanceDateTime);
        }
        
        public void UpdateCheque(System.Guid Id, decimal Amount, string PayTo, string AdminNationalCode, System.DateTime IssuanceDateTime, string Description) {
            base.Channel.UpdateCheque(Id, Amount, PayTo, AdminNationalCode, IssuanceDateTime, Description);
        }
        
        public System.Threading.Tasks.Task UpdateChequeAsync(System.Guid Id, decimal Amount, string PayTo, string AdminNationalCode, System.DateTime IssuanceDateTime, string Description) {
            return base.Channel.UpdateChequeAsync(Id, Amount, PayTo, AdminNationalCode, IssuanceDateTime, Description);
        }
        
        public void DeleteCheque(System.Guid Original_Id) {
            base.Channel.DeleteCheque(Original_Id);
        }
        
        public System.Threading.Tasks.Task DeleteChequeAsync(System.Guid Original_Id) {
            return base.Channel.DeleteChequeAsync(Original_Id);
        }
    }
}
