//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhajeNasirAccountingSystemReportClient.ChequeService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChequeSelectCommandResult", Namespace="http://schemas.datacontract.org/2004/07/KhajeNasirAccountingSystemWcfServiceAppli" +
        "cation")]
    [System.SerializableAttribute()]
    public partial class ChequeSelectCommandResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdminNationalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ConsecutiveNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime IssuanceDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayToField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdminNationalCode {
            get {
                return this.AdminNationalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AdminNationalCodeField, value) != true)) {
                    this.AdminNationalCodeField = value;
                    this.RaisePropertyChanged("AdminNationalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ConsecutiveNumber {
            get {
                return this.ConsecutiveNumberField;
            }
            set {
                if ((this.ConsecutiveNumberField.Equals(value) != true)) {
                    this.ConsecutiveNumberField = value;
                    this.RaisePropertyChanged("ConsecutiveNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime IssuanceDateTime {
            get {
                return this.IssuanceDateTimeField;
            }
            set {
                if ((this.IssuanceDateTimeField.Equals(value) != true)) {
                    this.IssuanceDateTimeField = value;
                    this.RaisePropertyChanged("IssuanceDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayTo {
            get {
                return this.PayToField;
            }
            set {
                if ((object.ReferenceEquals(this.PayToField, value) != true)) {
                    this.PayToField = value;
                    this.RaisePropertyChanged("PayTo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ChequeService.IChequeService")]
    public interface IChequeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChequeService/GetCheque", ReplyAction="http://tempuri.org/IChequeService/GetChequeResponse")]
        KhajeNasirAccountingSystemReportClient.ChequeService.ChequeSelectCommandResult[] GetCheque();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChequeService/GetCheque", ReplyAction="http://tempuri.org/IChequeService/GetChequeResponse")]
        System.Threading.Tasks.Task<KhajeNasirAccountingSystemReportClient.ChequeService.ChequeSelectCommandResult[]> GetChequeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChequeService/InsertCheque", ReplyAction="http://tempuri.org/IChequeService/InsertChequeResponse")]
        void InsertCheque(System.Guid Id, decimal Amount, string PayTo, string AdminNationalCode, System.DateTime IssuanceDateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChequeService/InsertCheque", ReplyAction="http://tempuri.org/IChequeService/InsertChequeResponse")]
        System.Threading.Tasks.Task InsertChequeAsync(System.Guid Id, decimal Amount, string PayTo, string AdminNationalCode, System.DateTime IssuanceDateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChequeService/UpdateCheque", ReplyAction="http://tempuri.org/IChequeService/UpdateChequeResponse")]
        void UpdateCheque(System.Guid Id, decimal Amount, string PayTo, string AdminNationalCode, System.DateTime IssuanceDateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChequeService/UpdateCheque", ReplyAction="http://tempuri.org/IChequeService/UpdateChequeResponse")]
        System.Threading.Tasks.Task UpdateChequeAsync(System.Guid Id, decimal Amount, string PayTo, string AdminNationalCode, System.DateTime IssuanceDateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChequeService/DeleteCheque", ReplyAction="http://tempuri.org/IChequeService/DeleteChequeResponse")]
        void DeleteCheque(System.Guid Original_Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChequeService/DeleteCheque", ReplyAction="http://tempuri.org/IChequeService/DeleteChequeResponse")]
        System.Threading.Tasks.Task DeleteChequeAsync(System.Guid Original_Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChequeServiceChannel : KhajeNasirAccountingSystemReportClient.ChequeService.IChequeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChequeServiceClient : System.ServiceModel.ClientBase<KhajeNasirAccountingSystemReportClient.ChequeService.IChequeService>, KhajeNasirAccountingSystemReportClient.ChequeService.IChequeService {
        
        public ChequeServiceClient() {
        }
        
        public ChequeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChequeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChequeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChequeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public KhajeNasirAccountingSystemReportClient.ChequeService.ChequeSelectCommandResult[] GetCheque() {
            return base.Channel.GetCheque();
        }
        
        public System.Threading.Tasks.Task<KhajeNasirAccountingSystemReportClient.ChequeService.ChequeSelectCommandResult[]> GetChequeAsync() {
            return base.Channel.GetChequeAsync();
        }
        
        public void InsertCheque(System.Guid Id, decimal Amount, string PayTo, string AdminNationalCode, System.DateTime IssuanceDateTime) {
            base.Channel.InsertCheque(Id, Amount, PayTo, AdminNationalCode, IssuanceDateTime);
        }
        
        public System.Threading.Tasks.Task InsertChequeAsync(System.Guid Id, decimal Amount, string PayTo, string AdminNationalCode, System.DateTime IssuanceDateTime) {
            return base.Channel.InsertChequeAsync(Id, Amount, PayTo, AdminNationalCode, IssuanceDateTime);
        }
        
        public void UpdateCheque(System.Guid Id, decimal Amount, string PayTo, string AdminNationalCode, System.DateTime IssuanceDateTime) {
            base.Channel.UpdateCheque(Id, Amount, PayTo, AdminNationalCode, IssuanceDateTime);
        }
        
        public System.Threading.Tasks.Task UpdateChequeAsync(System.Guid Id, decimal Amount, string PayTo, string AdminNationalCode, System.DateTime IssuanceDateTime) {
            return base.Channel.UpdateChequeAsync(Id, Amount, PayTo, AdminNationalCode, IssuanceDateTime);
        }
        
        public void DeleteCheque(System.Guid Original_Id) {
            base.Channel.DeleteCheque(Original_Id);
        }
        
        public System.Threading.Tasks.Task DeleteChequeAsync(System.Guid Original_Id) {
            return base.Channel.DeleteChequeAsync(Original_Id);
        }
    }
}
