//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhajeNasirAccountingSystemWindowsFormClient.Status {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Status.IStatus")]
    public interface IStatus {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatus/GetPersonBank", ReplyAction="http://tempuri.org/IStatus/GetPersonBankResponse")]
        KhajeNasirAccountingSystemReportClient.StatusService.OurBank GetPersonBank(string NationalCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatus/GetPersonBank", ReplyAction="http://tempuri.org/IStatus/GetPersonBankResponse")]
        System.Threading.Tasks.Task<KhajeNasirAccountingSystemReportClient.StatusService.OurBank> GetPersonBankAsync(string NationalCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatus/GetPeopleBank", ReplyAction="http://tempuri.org/IStatus/GetPeopleBankResponse")]
        KhajeNasirAccountingSystemReportClient.StatusService.OurBank GetPeopleBank();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatus/GetPeopleBank", ReplyAction="http://tempuri.org/IStatus/GetPeopleBankResponse")]
        System.Threading.Tasks.Task<KhajeNasirAccountingSystemReportClient.StatusService.OurBank> GetPeopleBankAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatus/GetTransactions", ReplyAction="http://tempuri.org/IStatus/GetTransactionsResponse")]
        KhajeNasirAccountingSystemReportClient.StatusService.Transaction[] GetTransactions(string NationalCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatus/GetTransactions", ReplyAction="http://tempuri.org/IStatus/GetTransactionsResponse")]
        System.Threading.Tasks.Task<KhajeNasirAccountingSystemReportClient.StatusService.Transaction[]> GetTransactionsAsync(string NationalCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatus/IsActive", ReplyAction="http://tempuri.org/IStatus/IsActiveResponse")]
        bool IsActive(string NationalCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatus/IsActive", ReplyAction="http://tempuri.org/IStatus/IsActiveResponse")]
        System.Threading.Tasks.Task<bool> IsActiveAsync(string NationalCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatus/SetActive", ReplyAction="http://tempuri.org/IStatus/SetActiveResponse")]
        void SetActive(string NationalCode, bool IsActive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatus/SetActive", ReplyAction="http://tempuri.org/IStatus/SetActiveResponse")]
        System.Threading.Tasks.Task SetActiveAsync(string NationalCode, bool IsActive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatus/LastLoginDate", ReplyAction="http://tempuri.org/IStatus/LastLoginDateResponse")]
        System.DateTime LastLoginDate(string NationalCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatus/LastLoginDate", ReplyAction="http://tempuri.org/IStatus/LastLoginDateResponse")]
        System.Threading.Tasks.Task<System.DateTime> LastLoginDateAsync(string NationalCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStatusChannel : KhajeNasirAccountingSystemWindowsFormClient.Status.IStatus, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StatusClient : System.ServiceModel.ClientBase<KhajeNasirAccountingSystemWindowsFormClient.Status.IStatus>, KhajeNasirAccountingSystemWindowsFormClient.Status.IStatus {
        
        public StatusClient() {
        }
        
        public StatusClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StatusClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StatusClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StatusClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public KhajeNasirAccountingSystemReportClient.StatusService.OurBank GetPersonBank(string NationalCode) {
            return base.Channel.GetPersonBank(NationalCode);
        }
        
        public System.Threading.Tasks.Task<KhajeNasirAccountingSystemReportClient.StatusService.OurBank> GetPersonBankAsync(string NationalCode) {
            return base.Channel.GetPersonBankAsync(NationalCode);
        }
        
        public KhajeNasirAccountingSystemReportClient.StatusService.OurBank GetPeopleBank() {
            return base.Channel.GetPeopleBank();
        }
        
        public System.Threading.Tasks.Task<KhajeNasirAccountingSystemReportClient.StatusService.OurBank> GetPeopleBankAsync() {
            return base.Channel.GetPeopleBankAsync();
        }
        
        public KhajeNasirAccountingSystemReportClient.StatusService.Transaction[] GetTransactions(string NationalCode) {
            return base.Channel.GetTransactions(NationalCode);
        }
        
        public System.Threading.Tasks.Task<KhajeNasirAccountingSystemReportClient.StatusService.Transaction[]> GetTransactionsAsync(string NationalCode) {
            return base.Channel.GetTransactionsAsync(NationalCode);
        }
        
        public bool IsActive(string NationalCode) {
            return base.Channel.IsActive(NationalCode);
        }
        
        public System.Threading.Tasks.Task<bool> IsActiveAsync(string NationalCode) {
            return base.Channel.IsActiveAsync(NationalCode);
        }
        
        public void SetActive(string NationalCode, bool IsActive) {
            base.Channel.SetActive(NationalCode, IsActive);
        }
        
        public System.Threading.Tasks.Task SetActiveAsync(string NationalCode, bool IsActive) {
            return base.Channel.SetActiveAsync(NationalCode, IsActive);
        }
        
        public System.DateTime LastLoginDate(string NationalCode) {
            return base.Channel.LastLoginDate(NationalCode);
        }
        
        public System.Threading.Tasks.Task<System.DateTime> LastLoginDateAsync(string NationalCode) {
            return base.Channel.LastLoginDateAsync(NationalCode);
        }
    }
}
