//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhajeNasirAccountingSystemWindowsFormClient.InstallementsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InstallementsService.IInstallementsService")]
    public interface IInstallementsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstallementsService/GetNonPayedInstallements", ReplyAction="http://tempuri.org/IInstallementsService/GetNonPayedInstallementsResponse")]
        KhajeNasirAccountingSystemReportClient.InstallemenetsService.InstallementsSelectCommandResult[] GetNonPayedInstallements(string NationalCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstallementsService/GetNonPayedInstallements", ReplyAction="http://tempuri.org/IInstallementsService/GetNonPayedInstallementsResponse")]
        System.Threading.Tasks.Task<KhajeNasirAccountingSystemReportClient.InstallemenetsService.InstallementsSelectCommandResult[]> GetNonPayedInstallementsAsync(string NationalCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstallementsService/GetLoanInstallements", ReplyAction="http://tempuri.org/IInstallementsService/GetLoanInstallementsResponse")]
        KhajeNasirAccountingSystemReportClient.InstallemenetsService.InstallementsSelectCommandResult[] GetLoanInstallements(System.Guid LoanTransactionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstallementsService/GetLoanInstallements", ReplyAction="http://tempuri.org/IInstallementsService/GetLoanInstallementsResponse")]
        System.Threading.Tasks.Task<KhajeNasirAccountingSystemReportClient.InstallemenetsService.InstallementsSelectCommandResult[]> GetLoanInstallementsAsync(System.Guid LoanTransactionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstallementsService/GetInstallements", ReplyAction="http://tempuri.org/IInstallementsService/GetInstallementsResponse")]
        KhajeNasirAccountingSystemReportClient.InstallemenetsService.InstallementsSelectCommandResult[] GetInstallements();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstallementsService/GetInstallements", ReplyAction="http://tempuri.org/IInstallementsService/GetInstallementsResponse")]
        System.Threading.Tasks.Task<KhajeNasirAccountingSystemReportClient.InstallemenetsService.InstallementsSelectCommandResult[]> GetInstallementsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstallementsService/InsertInstallements", ReplyAction="http://tempuri.org/IInstallementsService/InsertInstallementsResponse")]
        void InsertInstallements(System.Guid Id, System.Nullable<System.DateTime> PaymentDate, decimal Amount, System.Guid LoanTransactionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstallementsService/InsertInstallements", ReplyAction="http://tempuri.org/IInstallementsService/InsertInstallementsResponse")]
        System.Threading.Tasks.Task InsertInstallementsAsync(System.Guid Id, System.Nullable<System.DateTime> PaymentDate, decimal Amount, System.Guid LoanTransactionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstallementsService/UpdateInstallements", ReplyAction="http://tempuri.org/IInstallementsService/UpdateInstallementsResponse")]
        void UpdateInstallements(System.Guid Id, System.Nullable<System.DateTime> PaymentDate, decimal Amount, System.Guid LoanTransactionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstallementsService/UpdateInstallements", ReplyAction="http://tempuri.org/IInstallementsService/UpdateInstallementsResponse")]
        System.Threading.Tasks.Task UpdateInstallementsAsync(System.Guid Id, System.Nullable<System.DateTime> PaymentDate, decimal Amount, System.Guid LoanTransactionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstallementsService/DeleteInstallements", ReplyAction="http://tempuri.org/IInstallementsService/DeleteInstallementsResponse")]
        void DeleteInstallements(System.Guid Original_Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstallementsService/DeleteInstallements", ReplyAction="http://tempuri.org/IInstallementsService/DeleteInstallementsResponse")]
        System.Threading.Tasks.Task DeleteInstallementsAsync(System.Guid Original_Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstallementsService/PayInstallement", ReplyAction="http://tempuri.org/IInstallementsService/PayInstallementResponse")]
        void PayInstallement(System.Guid Original_Id, bool IsPayed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstallementsService/PayInstallement", ReplyAction="http://tempuri.org/IInstallementsService/PayInstallementResponse")]
        System.Threading.Tasks.Task PayInstallementAsync(System.Guid Original_Id, bool IsPayed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstallementsService/GetPeopleInstallements", ReplyAction="http://tempuri.org/IInstallementsService/GetPeopleInstallementsResponse")]
        KhajeNasirAccountingSystemReportClient.InstallemenetsService.View_Update1_PersonInstallement[] GetPeopleInstallements();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstallementsService/GetPeopleInstallements", ReplyAction="http://tempuri.org/IInstallementsService/GetPeopleInstallementsResponse")]
        System.Threading.Tasks.Task<KhajeNasirAccountingSystemReportClient.InstallemenetsService.View_Update1_PersonInstallement[]> GetPeopleInstallementsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstallementsService/AutomaticInstallement", ReplyAction="http://tempuri.org/IInstallementsService/AutomaticInstallementResponse")]
        void AutomaticInstallement(System.Guid LoanTransactionId, int Count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstallementsService/AutomaticInstallement", ReplyAction="http://tempuri.org/IInstallementsService/AutomaticInstallementResponse")]
        System.Threading.Tasks.Task AutomaticInstallementAsync(System.Guid LoanTransactionId, int Count);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInstallementsServiceChannel : KhajeNasirAccountingSystemWindowsFormClient.InstallementsService.IInstallementsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InstallementsServiceClient : System.ServiceModel.ClientBase<KhajeNasirAccountingSystemWindowsFormClient.InstallementsService.IInstallementsService>, KhajeNasirAccountingSystemWindowsFormClient.InstallementsService.IInstallementsService {
        
        public InstallementsServiceClient() {
        }
        
        public InstallementsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InstallementsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InstallementsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InstallementsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public KhajeNasirAccountingSystemReportClient.InstallemenetsService.InstallementsSelectCommandResult[] GetNonPayedInstallements(string NationalCode) {
            return base.Channel.GetNonPayedInstallements(NationalCode);
        }
        
        public System.Threading.Tasks.Task<KhajeNasirAccountingSystemReportClient.InstallemenetsService.InstallementsSelectCommandResult[]> GetNonPayedInstallementsAsync(string NationalCode) {
            return base.Channel.GetNonPayedInstallementsAsync(NationalCode);
        }
        
        public KhajeNasirAccountingSystemReportClient.InstallemenetsService.InstallementsSelectCommandResult[] GetLoanInstallements(System.Guid LoanTransactionId) {
            return base.Channel.GetLoanInstallements(LoanTransactionId);
        }
        
        public System.Threading.Tasks.Task<KhajeNasirAccountingSystemReportClient.InstallemenetsService.InstallementsSelectCommandResult[]> GetLoanInstallementsAsync(System.Guid LoanTransactionId) {
            return base.Channel.GetLoanInstallementsAsync(LoanTransactionId);
        }
        
        public KhajeNasirAccountingSystemReportClient.InstallemenetsService.InstallementsSelectCommandResult[] GetInstallements() {
            return base.Channel.GetInstallements();
        }
        
        public System.Threading.Tasks.Task<KhajeNasirAccountingSystemReportClient.InstallemenetsService.InstallementsSelectCommandResult[]> GetInstallementsAsync() {
            return base.Channel.GetInstallementsAsync();
        }
        
        public void InsertInstallements(System.Guid Id, System.Nullable<System.DateTime> PaymentDate, decimal Amount, System.Guid LoanTransactionId) {
            base.Channel.InsertInstallements(Id, PaymentDate, Amount, LoanTransactionId);
        }
        
        public System.Threading.Tasks.Task InsertInstallementsAsync(System.Guid Id, System.Nullable<System.DateTime> PaymentDate, decimal Amount, System.Guid LoanTransactionId) {
            return base.Channel.InsertInstallementsAsync(Id, PaymentDate, Amount, LoanTransactionId);
        }
        
        public void UpdateInstallements(System.Guid Id, System.Nullable<System.DateTime> PaymentDate, decimal Amount, System.Guid LoanTransactionId) {
            base.Channel.UpdateInstallements(Id, PaymentDate, Amount, LoanTransactionId);
        }
        
        public System.Threading.Tasks.Task UpdateInstallementsAsync(System.Guid Id, System.Nullable<System.DateTime> PaymentDate, decimal Amount, System.Guid LoanTransactionId) {
            return base.Channel.UpdateInstallementsAsync(Id, PaymentDate, Amount, LoanTransactionId);
        }
        
        public void DeleteInstallements(System.Guid Original_Id) {
            base.Channel.DeleteInstallements(Original_Id);
        }
        
        public System.Threading.Tasks.Task DeleteInstallementsAsync(System.Guid Original_Id) {
            return base.Channel.DeleteInstallementsAsync(Original_Id);
        }
        
        public void PayInstallement(System.Guid Original_Id, bool IsPayed) {
            base.Channel.PayInstallement(Original_Id, IsPayed);
        }
        
        public System.Threading.Tasks.Task PayInstallementAsync(System.Guid Original_Id, bool IsPayed) {
            return base.Channel.PayInstallementAsync(Original_Id, IsPayed);
        }
        
        public KhajeNasirAccountingSystemReportClient.InstallemenetsService.View_Update1_PersonInstallement[] GetPeopleInstallements() {
            return base.Channel.GetPeopleInstallements();
        }
        
        public System.Threading.Tasks.Task<KhajeNasirAccountingSystemReportClient.InstallemenetsService.View_Update1_PersonInstallement[]> GetPeopleInstallementsAsync() {
            return base.Channel.GetPeopleInstallementsAsync();
        }
        
        public void AutomaticInstallement(System.Guid LoanTransactionId, int Count) {
            base.Channel.AutomaticInstallement(LoanTransactionId, Count);
        }
        
        public System.Threading.Tasks.Task AutomaticInstallementAsync(System.Guid LoanTransactionId, int Count) {
            return base.Channel.AutomaticInstallementAsync(LoanTransactionId, Count);
        }
    }
}
