//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhajeNasirAccountingSystemWindowsFormClient.About {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="About.IAbout")]
    public interface IAbout {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAbout/Hello", ReplyAction="http://tempuri.org/IAbout/HelloResponse")]
        string Hello();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAbout/Hello", ReplyAction="http://tempuri.org/IAbout/HelloResponse")]
        System.Threading.Tasks.Task<string> HelloAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAbout/HowIsYourDatabase", ReplyAction="http://tempuri.org/IAbout/HowIsYourDatabaseResponse")]
        string HowIsYourDatabase();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAbout/HowIsYourDatabase", ReplyAction="http://tempuri.org/IAbout/HowIsYourDatabaseResponse")]
        System.Threading.Tasks.Task<string> HowIsYourDatabaseAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAboutChannel : KhajeNasirAccountingSystemWindowsFormClient.About.IAbout, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AboutClient : System.ServiceModel.ClientBase<KhajeNasirAccountingSystemWindowsFormClient.About.IAbout>, KhajeNasirAccountingSystemWindowsFormClient.About.IAbout {
        
        public AboutClient() {
        }
        
        public AboutClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AboutClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AboutClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AboutClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Hello() {
            return base.Channel.Hello();
        }
        
        public System.Threading.Tasks.Task<string> HelloAsync() {
            return base.Channel.HelloAsync();
        }
        
        public string HowIsYourDatabase() {
            return base.Channel.HowIsYourDatabase();
        }
        
        public System.Threading.Tasks.Task<string> HowIsYourDatabaseAsync() {
            return base.Channel.HowIsYourDatabaseAsync();
        }
    }
}
