//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhajeNasirAccountingSystemReportClient.InstallemenetsService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InstallementsSelectCommandResult", Namespace="http://schemas.datacontract.org/2004/07/KhajeNasirAccountingSystemWcfServiceAppli" +
        "cation")]
    [System.SerializableAttribute()]
    public partial class InstallementsSelectCommandResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPayedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid LoanTransactionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> PaymentDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPayed {
            get {
                return this.IsPayedField;
            }
            set {
                if ((this.IsPayedField.Equals(value) != true)) {
                    this.IsPayedField = value;
                    this.RaisePropertyChanged("IsPayed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid LoanTransactionId {
            get {
                return this.LoanTransactionIdField;
            }
            set {
                if ((this.LoanTransactionIdField.Equals(value) != true)) {
                    this.LoanTransactionIdField = value;
                    this.RaisePropertyChanged("LoanTransactionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PaymentDate {
            get {
                return this.PaymentDateField;
            }
            set {
                if ((this.PaymentDateField.Equals(value) != true)) {
                    this.PaymentDateField = value;
                    this.RaisePropertyChanged("PaymentDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="View_Update1_PersonInstallement", Namespace="http://schemas.datacontract.org/2004/07/KhajeNasirAccountingSystemWcfServiceAppli" +
        "cation")]
    [System.SerializableAttribute()]
    public partial class View_Update1_PersonInstallement : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid InstallementIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool InstallementIsPayedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid LoanIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NationalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> PaymentDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fullname {
            get {
                return this.FullnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullnameField, value) != true)) {
                    this.FullnameField = value;
                    this.RaisePropertyChanged("Fullname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid InstallementId {
            get {
                return this.InstallementIdField;
            }
            set {
                if ((this.InstallementIdField.Equals(value) != true)) {
                    this.InstallementIdField = value;
                    this.RaisePropertyChanged("InstallementId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool InstallementIsPayed {
            get {
                return this.InstallementIsPayedField;
            }
            set {
                if ((this.InstallementIsPayedField.Equals(value) != true)) {
                    this.InstallementIsPayedField = value;
                    this.RaisePropertyChanged("InstallementIsPayed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid LoanId {
            get {
                return this.LoanIdField;
            }
            set {
                if ((this.LoanIdField.Equals(value) != true)) {
                    this.LoanIdField = value;
                    this.RaisePropertyChanged("LoanId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NationalCode {
            get {
                return this.NationalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.NationalCodeField, value) != true)) {
                    this.NationalCodeField = value;
                    this.RaisePropertyChanged("NationalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PaymentDate {
            get {
                return this.PaymentDateField;
            }
            set {
                if ((this.PaymentDateField.Equals(value) != true)) {
                    this.PaymentDateField = value;
                    this.RaisePropertyChanged("PaymentDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InstallemenetsService.IInstallementsService")]
    public interface IInstallementsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstallementsService/GetNonPayedInstallements", ReplyAction="http://tempuri.org/IInstallementsService/GetNonPayedInstallementsResponse")]
        KhajeNasirAccountingSystemReportClient.InstallemenetsService.InstallementsSelectCommandResult[] GetNonPayedInstallements(string NationalCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstallementsService/GetNonPayedInstallements", ReplyAction="http://tempuri.org/IInstallementsService/GetNonPayedInstallementsResponse")]
        System.Threading.Tasks.Task<KhajeNasirAccountingSystemReportClient.InstallemenetsService.InstallementsSelectCommandResult[]> GetNonPayedInstallementsAsync(string NationalCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstallementsService/GetLoanInstallements", ReplyAction="http://tempuri.org/IInstallementsService/GetLoanInstallementsResponse")]
        KhajeNasirAccountingSystemReportClient.InstallemenetsService.InstallementsSelectCommandResult[] GetLoanInstallements(System.Guid LoanTransactionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstallementsService/GetLoanInstallements", ReplyAction="http://tempuri.org/IInstallementsService/GetLoanInstallementsResponse")]
        System.Threading.Tasks.Task<KhajeNasirAccountingSystemReportClient.InstallemenetsService.InstallementsSelectCommandResult[]> GetLoanInstallementsAsync(System.Guid LoanTransactionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstallementsService/GetInstallements", ReplyAction="http://tempuri.org/IInstallementsService/GetInstallementsResponse")]
        KhajeNasirAccountingSystemReportClient.InstallemenetsService.InstallementsSelectCommandResult[] GetInstallements();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstallementsService/GetInstallements", ReplyAction="http://tempuri.org/IInstallementsService/GetInstallementsResponse")]
        System.Threading.Tasks.Task<KhajeNasirAccountingSystemReportClient.InstallemenetsService.InstallementsSelectCommandResult[]> GetInstallementsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstallementsService/InsertInstallements", ReplyAction="http://tempuri.org/IInstallementsService/InsertInstallementsResponse")]
        void InsertInstallements(System.Guid Id, System.Nullable<System.DateTime> PaymentDate, decimal Amount, System.Guid LoanTransactionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstallementsService/InsertInstallements", ReplyAction="http://tempuri.org/IInstallementsService/InsertInstallementsResponse")]
        System.Threading.Tasks.Task InsertInstallementsAsync(System.Guid Id, System.Nullable<System.DateTime> PaymentDate, decimal Amount, System.Guid LoanTransactionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstallementsService/UpdateInstallements", ReplyAction="http://tempuri.org/IInstallementsService/UpdateInstallementsResponse")]
        void UpdateInstallements(System.Guid Id, System.Nullable<System.DateTime> PaymentDate, decimal Amount, System.Guid LoanTransactionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstallementsService/UpdateInstallements", ReplyAction="http://tempuri.org/IInstallementsService/UpdateInstallementsResponse")]
        System.Threading.Tasks.Task UpdateInstallementsAsync(System.Guid Id, System.Nullable<System.DateTime> PaymentDate, decimal Amount, System.Guid LoanTransactionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstallementsService/DeleteInstallements", ReplyAction="http://tempuri.org/IInstallementsService/DeleteInstallementsResponse")]
        void DeleteInstallements(System.Guid Original_Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstallementsService/DeleteInstallements", ReplyAction="http://tempuri.org/IInstallementsService/DeleteInstallementsResponse")]
        System.Threading.Tasks.Task DeleteInstallementsAsync(System.Guid Original_Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstallementsService/PayInstallement", ReplyAction="http://tempuri.org/IInstallementsService/PayInstallementResponse")]
        void PayInstallement(System.Guid Original_Id, bool IsPayed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstallementsService/PayInstallement", ReplyAction="http://tempuri.org/IInstallementsService/PayInstallementResponse")]
        System.Threading.Tasks.Task PayInstallementAsync(System.Guid Original_Id, bool IsPayed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstallementsService/GetPeopleInstallements", ReplyAction="http://tempuri.org/IInstallementsService/GetPeopleInstallementsResponse")]
        KhajeNasirAccountingSystemReportClient.InstallemenetsService.View_Update1_PersonInstallement[] GetPeopleInstallements();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstallementsService/GetPeopleInstallements", ReplyAction="http://tempuri.org/IInstallementsService/GetPeopleInstallementsResponse")]
        System.Threading.Tasks.Task<KhajeNasirAccountingSystemReportClient.InstallemenetsService.View_Update1_PersonInstallement[]> GetPeopleInstallementsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstallementsService/AutomaticInstallement", ReplyAction="http://tempuri.org/IInstallementsService/AutomaticInstallementResponse")]
        void AutomaticInstallement(System.Guid LoanTransactionId, int Count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstallementsService/AutomaticInstallement", ReplyAction="http://tempuri.org/IInstallementsService/AutomaticInstallementResponse")]
        System.Threading.Tasks.Task AutomaticInstallementAsync(System.Guid LoanTransactionId, int Count);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInstallementsServiceChannel : KhajeNasirAccountingSystemReportClient.InstallemenetsService.IInstallementsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InstallementsServiceClient : System.ServiceModel.ClientBase<KhajeNasirAccountingSystemReportClient.InstallemenetsService.IInstallementsService>, KhajeNasirAccountingSystemReportClient.InstallemenetsService.IInstallementsService {
        
        public InstallementsServiceClient() {
        }
        
        public InstallementsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InstallementsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InstallementsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InstallementsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public KhajeNasirAccountingSystemReportClient.InstallemenetsService.InstallementsSelectCommandResult[] GetNonPayedInstallements(string NationalCode) {
            return base.Channel.GetNonPayedInstallements(NationalCode);
        }
        
        public System.Threading.Tasks.Task<KhajeNasirAccountingSystemReportClient.InstallemenetsService.InstallementsSelectCommandResult[]> GetNonPayedInstallementsAsync(string NationalCode) {
            return base.Channel.GetNonPayedInstallementsAsync(NationalCode);
        }
        
        public KhajeNasirAccountingSystemReportClient.InstallemenetsService.InstallementsSelectCommandResult[] GetLoanInstallements(System.Guid LoanTransactionId) {
            return base.Channel.GetLoanInstallements(LoanTransactionId);
        }
        
        public System.Threading.Tasks.Task<KhajeNasirAccountingSystemReportClient.InstallemenetsService.InstallementsSelectCommandResult[]> GetLoanInstallementsAsync(System.Guid LoanTransactionId) {
            return base.Channel.GetLoanInstallementsAsync(LoanTransactionId);
        }
        
        public KhajeNasirAccountingSystemReportClient.InstallemenetsService.InstallementsSelectCommandResult[] GetInstallements() {
            return base.Channel.GetInstallements();
        }
        
        public System.Threading.Tasks.Task<KhajeNasirAccountingSystemReportClient.InstallemenetsService.InstallementsSelectCommandResult[]> GetInstallementsAsync() {
            return base.Channel.GetInstallementsAsync();
        }
        
        public void InsertInstallements(System.Guid Id, System.Nullable<System.DateTime> PaymentDate, decimal Amount, System.Guid LoanTransactionId) {
            base.Channel.InsertInstallements(Id, PaymentDate, Amount, LoanTransactionId);
        }
        
        public System.Threading.Tasks.Task InsertInstallementsAsync(System.Guid Id, System.Nullable<System.DateTime> PaymentDate, decimal Amount, System.Guid LoanTransactionId) {
            return base.Channel.InsertInstallementsAsync(Id, PaymentDate, Amount, LoanTransactionId);
        }
        
        public void UpdateInstallements(System.Guid Id, System.Nullable<System.DateTime> PaymentDate, decimal Amount, System.Guid LoanTransactionId) {
            base.Channel.UpdateInstallements(Id, PaymentDate, Amount, LoanTransactionId);
        }
        
        public System.Threading.Tasks.Task UpdateInstallementsAsync(System.Guid Id, System.Nullable<System.DateTime> PaymentDate, decimal Amount, System.Guid LoanTransactionId) {
            return base.Channel.UpdateInstallementsAsync(Id, PaymentDate, Amount, LoanTransactionId);
        }
        
        public void DeleteInstallements(System.Guid Original_Id) {
            base.Channel.DeleteInstallements(Original_Id);
        }
        
        public System.Threading.Tasks.Task DeleteInstallementsAsync(System.Guid Original_Id) {
            return base.Channel.DeleteInstallementsAsync(Original_Id);
        }
        
        public void PayInstallement(System.Guid Original_Id, bool IsPayed) {
            base.Channel.PayInstallement(Original_Id, IsPayed);
        }
        
        public System.Threading.Tasks.Task PayInstallementAsync(System.Guid Original_Id, bool IsPayed) {
            return base.Channel.PayInstallementAsync(Original_Id, IsPayed);
        }
        
        public KhajeNasirAccountingSystemReportClient.InstallemenetsService.View_Update1_PersonInstallement[] GetPeopleInstallements() {
            return base.Channel.GetPeopleInstallements();
        }
        
        public System.Threading.Tasks.Task<KhajeNasirAccountingSystemReportClient.InstallemenetsService.View_Update1_PersonInstallement[]> GetPeopleInstallementsAsync() {
            return base.Channel.GetPeopleInstallementsAsync();
        }
        
        public void AutomaticInstallement(System.Guid LoanTransactionId, int Count) {
            base.Channel.AutomaticInstallement(LoanTransactionId, Count);
        }
        
        public System.Threading.Tasks.Task AutomaticInstallementAsync(System.Guid LoanTransactionId, int Count) {
            return base.Channel.AutomaticInstallementAsync(LoanTransactionId, Count);
        }
    }
}
