//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhajeNasirAccountingSystemWindowsFormClient.LogService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LogService.ILogService")]
    public interface ILogService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogService/GetTopLogs", ReplyAction="http://tempuri.org/ILogService/GetTopLogsResponse")]
        KhajeNasirAccountingSystemReportClient.DatabaseLogsService.LogSet_SelectResult[] GetTopLogs(int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogService/GetTopLogs", ReplyAction="http://tempuri.org/ILogService/GetTopLogsResponse")]
        System.Threading.Tasks.Task<KhajeNasirAccountingSystemReportClient.DatabaseLogsService.LogSet_SelectResult[]> GetTopLogsAsync(int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogService/InsertLog", ReplyAction="http://tempuri.org/ILogService/InsertLogResponse")]
        void InsertLog(string NationalCode, string Description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogService/InsertLog", ReplyAction="http://tempuri.org/ILogService/InsertLogResponse")]
        System.Threading.Tasks.Task InsertLogAsync(string NationalCode, string Description);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILogServiceChannel : KhajeNasirAccountingSystemWindowsFormClient.LogService.ILogService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LogServiceClient : System.ServiceModel.ClientBase<KhajeNasirAccountingSystemWindowsFormClient.LogService.ILogService>, KhajeNasirAccountingSystemWindowsFormClient.LogService.ILogService {
        
        public LogServiceClient() {
        }
        
        public LogServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LogServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public KhajeNasirAccountingSystemReportClient.DatabaseLogsService.LogSet_SelectResult[] GetTopLogs(int count) {
            return base.Channel.GetTopLogs(count);
        }
        
        public System.Threading.Tasks.Task<KhajeNasirAccountingSystemReportClient.DatabaseLogsService.LogSet_SelectResult[]> GetTopLogsAsync(int count) {
            return base.Channel.GetTopLogsAsync(count);
        }
        
        public void InsertLog(string NationalCode, string Description) {
            base.Channel.InsertLog(NationalCode, Description);
        }
        
        public System.Threading.Tasks.Task InsertLogAsync(string NationalCode, string Description) {
            return base.Channel.InsertLogAsync(NationalCode, Description);
        }
    }
}
